services:
  scraper:
    image: "cc_daily_news_scrape"
    ports:
      - "5000:5000"
    env_file:
      - stack.env
    restart: on-failure
    networks:
      - n8n
    volumes:
      - NAS:/app/nas_data

volumes:
  NAS:
    external: true

networks:
  n8n:
    external: true
